### ISSUE TITLE
Another Credit Card

### ISSUE THREAD

**Issue by lucalves** [gabriellamas/Fancy-Checkout#7]
Good night.

I would like to know if you have how I insert the animation with another card, for example with the Nubank card design. How can I do this? Or it will be later in some update?

Thank you.

**Comment by gabriellamas** [comment]
If you understand CSS and SASS you can change the style of the card. But I want in the future to put some layout options

**Comment by lucalves** [comment]
Okay, @gabriellamas. I'll try to do this. Thanks for the answer.
